# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Phase-2 (code-based) grounding regression tests on real documents.

Grounded extraction has three phases (see :mod:`dgml_core.grounded`): phase 1
is the LLM emitting ``{text, page}`` per value, phase 2 is the *code-based*
matcher (:func:`dgml_core.matching.run_phase2_matching`) assigning bounding
boxes by matching value text against OCR word boxes, and phase 3 is a
per-page LLM that localizes whatever phase 2 left unmatched. These tests
exercise phase 2 only — no LLM, no network — against OCR captured from
real documents, so we can (a) measure how much grounding the deterministic
matcher achieves and (b) lock it against regression.

Each case under ``fixtures/grounding/<case>/`` carries:

  - ``inputs.json`` — the phase-1 input (real extracted values with bboxes
    stripped and locations collapsed to one entry per (leaf, page), the
    shape phase 1 emits) plus the layout hint and source metadata.
  - ``page_text/page_N.json`` — the document's real OCR word boxes.
  - ``expected_phase2.json`` — the golden: every (leaf, page) the matcher
    currently resolves, mapped to its pixel-exact bounding boxes.

Failure modes are deliberately distinct:

  - **Regression (hard fail):** a (leaf, page) recorded in the golden is
    no longer matched, or its bounding boxes changed. The matcher got
    worse or moved a box — investigate before touching the snapshot.
  - **Improvement (fail, easy to accept):** the matcher now resolves
    locations not in the golden. Coverage went up; re-run with
    ``DGML_UPDATE_GROUNDING_SNAPSHOTS=1`` to bank the gain in the snapshot.

To regenerate goldens after an intentional matcher change::

    DGML_UPDATE_GROUNDING_SNAPSHOTS=1 uv run pytest \
        packages/dgml/tests/test_grounding_real_docs.py

Review the resulting diff: added lines are new matches; removed/changed
lines are losses that warrant scrutiny.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import pytest
from dgml_core import layout
from dgml_core.matching import _walk_leaves, path_to_str, run_phase2_matching
from dgml_core.storage import Workspace

FIXTURES = Path(__file__).parent / "fixtures" / "grounding"
CASES = ["raul_terrill", "interior_design"]
UPDATE_ENV = "DGML_UPDATE_GROUNDING_SNAPSHOTS"

# Per-case floor on the phase-2 match rate. The exact snapshot already
# pins the matched set; this is a coarser, human-readable guard that the
# code-based matcher keeps grounding at least this share of locations.
MIN_MATCH_RATE = {
    "raul_terrill": 0.95,
    "interior_design": 0.96,
}

MatchedUnits = dict[str, list[list[float]]]


def _matched_units(values: dict[str, Any]) -> MatchedUnits:
    """Map every phase-2-resolved (leaf, page) to its bounding boxes.

    A leaf's locations on a page are "matched" only when every entry has
    a ``bounding_box`` — an unmatched task is left as a single
    ``{page_number}`` placeholder, which we skip."""
    out: MatchedUnits = {}
    for path, leaf in _walk_leaves(values):
        by_page: dict[int, list[Any]] = {}
        for loc in leaf["locations"]:
            by_page.setdefault(int(loc["page_number"]), []).append(loc)
        for page in sorted(by_page):
            boxes = [loc.get("bounding_box") for loc in by_page[page]]
            if boxes and all(b is not None for b in boxes):
                out[f"{path_to_str(path)} @p{page}"] = [[float(c) for c in b] for b in boxes]
    return out


def _load_workspace(tmp_path: Path, case: str) -> tuple[Workspace, dict[str, Any]]:
    """Build a throwaway workspace seeded only with the case's OCR page
    text — all the matcher reads — and return it with the parsed inputs."""
    inputs = json.loads((FIXTURES / case / "inputs.json").read_text())
    ws = Workspace(root=tmp_path / "ws")
    file_id = inputs["source"]["file_id"]
    text_prefix = layout.file_text_prefix(file_id)
    for page_text in sorted((FIXTURES / case / "page_text").glob("page_*.json")):
        ws.blobs.put_blob(f"{text_prefix}{page_text.name}", page_text.read_bytes())
    return ws, inputs


def _write_golden(path: Path, total: int, matched: MatchedUnits) -> None:
    payload = {
        "_comment": (
            "Generated by test_grounding_real_docs.py with "
            f"{UPDATE_ENV}=1. Phase-2 (code-based) matcher output: "
            "{'<path> @p<page>': [bbox, ...]} in integer image pixels "
            "[left, top, right, bottom]. Do not hand-edit."
        ),
        "total_locations": total,
        "matched_count": len(matched),
        "matched": dict(sorted(matched.items())),
    }
    path.write_text(json.dumps(payload, indent=2) + "\n")


@pytest.mark.parametrize("case", CASES)
def test_phase2_grounding_real_doc(case: str, tmp_path: Path) -> None:
    ws, inputs = _load_workspace(tmp_path, case)
    file_id = inputs["source"]["file_id"]

    result = run_phase2_matching(ws, file_id, inputs["phase1"], layout=inputs["layout"])
    current = _matched_units(result.values)
    total = result.stats.total_locations
    rate = len(current) / total if total else 0.0
    golden_path = FIXTURES / case / "expected_phase2.json"

    if os.environ.get(UPDATE_ENV) or not golden_path.exists():
        _write_golden(golden_path, total, current)
        pytest.skip(f"[{case}] wrote snapshot: {len(current)}/{total} matched ({rate:.1%})")

    golden = json.loads(golden_path.read_text())
    expected: MatchedUnits = golden["matched"]

    # The total number of (leaf, page) tasks is structural — if it drifts,
    # the fixture's phase-1 input changed and the snapshot is meaningless.
    assert total == golden["total_locations"], (
        f"[{case}] phase-1 task count changed: {total} != {golden['total_locations']}. "
        "Re-bootstrap the fixture inputs."
    )

    regressions: list[str] = []
    for key, boxes in expected.items():
        if key not in current:
            regressions.append(f"  LOST     {key}  (was {boxes})")
        elif current[key] != boxes:
            regressions.append(
                f"  CHANGED  {key}\n    expected {boxes}\n    got      {current[key]}"
            )
    additions = sorted(k for k in current if k not in expected)

    print(f"\n[{case}] phase-2 matched {len(current)}/{total} ({rate:.1%})")

    # Hard floor on match rate — a coarse guard independent of the snapshot.
    assert rate >= MIN_MATCH_RATE[case], (
        f"[{case}] phase-2 match rate {rate:.1%} fell below floor {MIN_MATCH_RATE[case]:.0%}"
    )

    if regressions:
        pytest.fail(
            f"[{case}] phase-2 grounding REGRESSED — "
            f"{len(regressions)} previously-matched location(s) lost or moved:\n"
            + "\n".join(regressions)
            + "\n\nThis is a hard failure: the matcher got worse. Investigate "
            "matching.py before regenerating the snapshot."
        )

    if additions:
        pytest.fail(
            f"[{case}] phase-2 grounding IMPROVED — {len(additions)} new "
            f"location(s) matched that aren't in the snapshot:\n"
            + "\n".join(f"  NEW  {k}" for k in additions)
            + f"\n\nCoverage went up. Lock it in by re-running with "
            f"{UPDATE_ENV}=1."
        )
