# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Record ids: generating them, and what makes one valid.

A File or DocSet id is generated by :func:`new_id` as 12 base-36 characters, but that is
not the *limit* of what one may be: a caller can supply their own with
``file add --id invoice-2024-q1``, so :func:`is_record_id` accepts a wider grammar of
which the generated form is a strict subset. That subset relationship is what lets the
grammar widen without a migration — every id already in every workspace stays valid.

The rule is deliberately the same one :mod:`dgml_core.workspace_id` applies to
workspace ids, but it is spelled out here rather than imported: the two are different
namespaces and are free to diverge, and importing would assert they never can.
"""

from __future__ import annotations

import re
import secrets
import string

ID_ALPHABET = string.ascii_lowercase + string.digits
ID_LENGTH = 12

#: What a File or DocSet id may look like — the **intersection** of what every storage
#: backend accepts, so an id means the same thing on local disk, S3 or MongoDB and a
#: workspace stays portable between them.
#:
#: No dot, separator or whitespace, because an id is a single segment of a blob key;
#: ``/`` in particular is a delimiter in ``layout.pair_id`` (``<docset>/<file>``) and in
#: the ``dgmlx://`` scheme, so one inside an id would not survive the round trip.
#:
#: Lowercase is set by the *strictest* backend rather than by all of them: a
#: case-insensitive filesystem would let ``Notes`` and ``notes`` collide as directory
#: names, while S3 keys and Mongo ``_id``\ s are case-sensitive and would keep them
#: distinct. Allowing case would make an id mean different things on different backends.
#:
#: Anchored with ``\Z`` rather than ``$`` so a trailing newline is not an id.
_RECORD_ID_RE = re.compile(r"[a-z0-9][a-z0-9_-]{2,39}\Z")

#: The rule in :data:`_RECORD_ID_RE`, in words. One source of truth for every message
#: that has to tell a caller why their id was rejected.
RECORD_ID_SHAPE = (
    "3 to 40 characters using only lowercase letters, digits, hyphens and "
    "underscores, and starting with a letter or digit"
)


def new_id() -> str:
    """Return a fresh 12-char base-36 ID (lowercase letters + digits).

    Always satisfies :func:`is_record_id`. Not collision-checked — a caller assigning
    an id to a record is responsible for that, which for a *generated* id is moot (~62
    bits from :mod:`secrets`) and for a *supplied* one is :meth:`FileStore.add`'s job."""
    return "".join(secrets.choice(ID_ALPHABET) for _ in range(ID_LENGTH))


def is_record_id(value: str) -> bool:
    """Whether ``value`` is a well-formed File/DocSet id (:data:`RECORD_ID_SHAPE`).

    Wider than what :func:`new_id` generates, because a caller may supply their own. Says
    nothing about whether a record with this id *exists* — that is a store lookup."""
    return _RECORD_ID_RE.match(value) is not None
